cs:
  label: Computer Science
  permalink: /cs
  description: Computer Science tag description

data-structure:
  label: Data Structure
  permalink: /data-structure
  description: Data Structure tag description

network:
  label: Network
  permalink: /network
  description: Network tag description

java:
  label: Java
  permalink: /java
  description: Java tag description

spring:
  label: Spring
  permalink: /spring
  description: Spring Framework tag description

jpa:
  label: JPA
  permalink: /jpa
  description: JPA tag description

db:
  label: Database
  permalink: /db
  description: Database tag description

cache:
  label: Cache
  permalink: /cache
  description: Cache tag description

mysql:
  label: MySQL
  permalink: /mysql
  description: MySQL tag description

redis:
  label: Redis
  permalink: /redis
  description: Redis tag description